services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_NAME=yourdb
      - DB_USER=youruser
      - DB_PASS=yourpass
      - REDIS_HOST=redis
      - ES_HOST=elasticsearch
    depends_on:
      db:
        condition: service_healthy
      elasticsearch:
        condition: service_started
      redis:
        condition: service_started
    restart: on-failure

  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: yourdb
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpass
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U youruser"]
      interval: 5s
      retries: 5

  elasticsearch:
    image: elasticsearch:9.4.0
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false

  redis:
    image: redis:latest
    ports:
      - "6379:6379"