spring:
  application:
    name: app
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:yourdb}
    username: ${DB_USER:youruser}
    password: ${DB_PASS:yourpass}
  liquibase:
    drop-first: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379
    elasticsearch:
      repositories:
        enabled: true

  elasticsearch:
    uris: http://${ES_HOST:localhost}:9200

  cache:
    type: redis
    redis:
      enable-statistics: false


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.elasticsearch.ElasticsearchDataAutoConfiguration
      - org.springframework.boot.autoconfigure.elasticsearch.ElasticsearchClientAutoConfiguration
      - org.springframework.boot.autoconfigure.data.elasticsearch.ElasticsearchRepositoriesAutoConfiguration
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: ${STMP_MAIL_USERNAME}
    password: ${STMP_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true
  show-actuator: false
security:              # ← root level, not spring.security
  jwt:
    secret-key: ${JWT_SECRET}
    access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:900000}
    refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:604800000}
  oauth2:
    client:
      registration:
        google:
          client-id: 997401268996-0m9m2t8fq89rpmeer23h4h5tvh3crl3i.apps.googleusercontent.com
          client-secret: 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
          scope:
            - openid
            - profile
            - email

logging:
  level:
    org.springframework.security: DEBUG
    com.e_commerce: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.jdbc: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: when-authorized
      #SECERT: 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
      #ID: 997401268996-0m9m2t8fq89rpmeer23h4h5tvh3crl3i.apps.googleusercontent.com